DASH-150 add bitpay handle to payments job
fioprotocol/fio-dashboard pull request #1030
Opened 2023-02-07 07:26 UTC by orkhan-huseyn

2023-02-07 16:02 UTC, vmkarpenko approved these changes

2023-02-08 13:49 UTC, vmkarpenko approved these changes

2023-02-08 15:09 UTC, trukhilio requested changes
Check comment. Need to be discussed

2023-02-08 15:09 UTC, trukhilio commented on server/src/jobs/payments.mjs
> +          await order.update(
I assume if we are trying to retrieve data like from webhook we should reuse webhook logic for updating the payment and order status to get the same result. Because there is missing BlockchainTransaction creation table row.

2026-05-21 17:27 UTC, closed without merging