DASH-981 Update ledger confirm dialog
fioprotocol/fio-dashboard pull request #1637
Opened 2024-05-15 09:06 UTC by sardonyxwt

2024-05-15 11:30 UTC, trukhilio requested changes
Check comments

2024-05-15 11:30 UTC, trukhilio commented on client/src/components/Modal/ConnectionModal/ConnectionModal.tsx
> +  console.error(action, data, fee, oracleFee);
Remove console

2024-05-15 11:30 UTC, trukhilio commented on client/src/components/Modal/ConnectionModal/ConnectionModal.tsx
> +    if (action === CONFIRM_LEDGER_ACTIONS.DETAILED_FIO_REQUEST) {
For the decrypt action, we will not show fields because some of them are encrypted and there is no need to display this information. We will only show the message without any fields.

2024-05-15 11:30 UTC, trukhilio commented on client/src/pages/AddSocialMediaLinksPage/AddSocialMediaLinksPage.tsx
> -    onRetry,
Why did you remove `onRetry`?

2024-05-15 19:40 UTC, sardonyxwt commented on client/src/components/Modal/ConnectionModal/ConnectionModal.tsx
> +      } = data as NFTTokenDoublet;
In ledger this fields omitted

2024-05-15 19:40 UTC, sardonyxwt commented on client/src/components/Modal/ConnectionModal/ConnectionModal.tsx
> +  console.error(action, data, fee, oracleFee);
Done

2024-05-15 19:40 UTC, sardonyxwt commented on client/src/components/Modal/ConnectionModal/ConnectionModal.tsx
> +    if (action === CONFIRM_LEDGER_ACTIONS.DETAILED_FIO_REQUEST) {
Done

2024-05-15 19:40 UTC, sardonyxwt commented on client/src/pages/AddSocialMediaLinksPage/AddSocialMediaLinksPage.tsx
> -    onRetry,
Function not used

2024-05-16 07:48 UTC, trukhilio approved these changes

2024-05-16 07:48 UTC, merged