DASH-969 Add buy fio tokens tile
fioprotocol/fio-dashboard pull request #1759
Opened 2024-07-30 11:02 UTC by sardonyxwt

2024-08-01 11:30 UTC, trukhilio requested changes
Check comments

2024-08-01 11:30 UTC, trukhilio commented on client/src/pages/WalletsPage/WalletsPage.tsx
> -        <TotalBalanceBadge
Why did you remove this. It should be used for mobile UI.

2024-08-01 11:30 UTC, trukhilio commented on client/src/pages/WalletsPage/components/NeedTokensBadge.tsx
> +const TotalBalanceBadge: FC = () => {
Rename component to NeedTokensBadge. Use named export here.

2024-08-01 11:37 UTC, psystrpla commented on client/src/pages/WalletsPage/WalletsPage.tsx
> -        <TotalBalanceBadge
No in mobile view we have two blocks (Bug I think)

2024-08-01 11:40 UTC, trukhilio commented on client/src/pages/WalletsPage/WalletsPage.tsx
> -        <TotalBalanceBadge
It's bug to show 2-nd one. Main reason is that to show balance after the list of wallets before Welcome component.
<img width="314" alt="Screenshot 2024-08-01 at 14 39 00" src="https://github.com/user-attachments/assets/b552b455-8059-471c-a2f9-9d4966998451">

2024-08-01 11:40 UTC, sardonyxwt commented on client/src/pages/WalletsPage/WalletsPage.tsx
> -        <TotalBalanceBadge
We have duplicate block in mobile view

2024-08-01 11:41 UTC, trukhilio commented on client/src/pages/WalletsPage/WalletsPage.tsx
> -        <TotalBalanceBadge
For mobile view let's remove 2nd one.

2024-08-05 12:02 UTC, trukhilio approved these changes

2024-08-05 14:24 UTC, merged