BD-2652 update email
fioprotocol/fio-dashboard pull request #338
Opened 2021-11-12 13:10 UTC by trukhilio

- Refactor settings page architecture

2021-11-18 07:44 UTC, andreyvEze commented on server/src/router.mjs
> +router.post('/users/updateEmailRevert', checkAuth, routes.users.updateEmailRevert);
let's use hyphens to separate the word in uri. (not camelCase, so - 'update-email-revert')

2021-11-18 07:47 UTC, andreyvEze commented on client/src/pages/SettingsPage/components/ChangeEmail/ChangeEmailForm.tsx
> +  // todo: set proper props
yes please :)

2021-11-18 07:52 UTC, andreyvEze commented on client/src/pages/VerifyConfirmGatePage/VerifyConfirmGatePage.tsx
> +  history: History;
we should use `RouteComponentProps`

2021-11-18 07:58 UTC, andreyvEze commented on client/src/pages/VerifyConfirmGatePage/VerifyConfirmGatePage.tsx
> +  const { id, updatedEmail = '' } = user || {};
please refactor this to check for `user != null`  below `if (isActiveUser)` check, and show loader in this case. then you not need to use `user || {}`, just use `user.id` `user.updatedEmail`

2021-11-18 08:00 UTC, andreyvEze commented on client/src/pages/VerifyEmailPage/VerifyEmailPage.tsx
> +  console.log(lastAuthData);
remove

2021-11-18 08:00 UTC, andreyvEze commented on client/src/pages/VerifyEmailPage/VerifyEmailPage.tsx
> +    // clearCachedUser,
?

2021-11-18 08:03 UTC, andreyvEze commented on client/src/pages/VerifyEmailPage/VerifyEmailPage.tsx
> +    if (profileRefreshed) updateEmail(hash);
why do we need to do this on `profileRefreshed`?

2021-11-18 08:04 UTC, andreyvEze commented on client/src/pages/VerifyEmailPage/VerifyEmailPage.tsx
> +        resetLastAuthData();
I assume you need to put `clearCachedUser` here too

2021-11-18 08:09 UTC, andreyvEze commented on client/src/util/auth.ts
> +export const emailAvailable = async (
not sure it should be in util, could we put it in the `apis.auth`?

2021-11-18 08:13 UTC, andreyvEze commented on client/src/util/hooks.ts
> +      return;
remove `return` and change isNotActiveUser selector logic to check for `NotActive` statuses not just `!== 'ACTIVE'`

2021-11-18 08:15 UTC, andreyvEze commented on server/src/services/emailSender.mjs
> +        delete sendData.updateEmail;
why do we need to remove this and why it is not in the if case part?

2021-11-18 08:18 UTC, andreyvEze commented on server/src/services/users/Info.mjs
> +        })) || {};
refactor this, `const { data: { newEmail } } = {}` would fail, just get the action and check for it

2021-11-18 08:21 UTC, andreyvEze commented on server/src/router.mjs
> +router.post('/users/updateEmail', routes.users.updateEmail);
you should remove this and send request to `/actions/:hash`, see how confirm email works. (you need to create method in the Action model)

2021-11-18 08:22 UTC, andreyvEze commented on server/src/services/users/UpdateEmail.mjs
> +import Sequelize from 'sequelize';
you should remove this

2021-11-18 08:24 UTC, andreyvEze commented on server/src/services/users/UpdateEmailRequest.mjs
> +          id: ['required', 'string'],
remove this, you should take user id from the context (`this.context.id`)

2021-11-18 08:25 UTC, andreyvEze commented on server/src/services/users/UpdateEmailRequest.mjs
> +    const action = await new Action({
this should be below user search

2021-11-18 08:26 UTC, andreyvEze commented on server/src/services/users/UpdateEmailRequest.mjs
> +      where: { status: { [Op.ne]: User.STATUS.BLOCKED } },
I assume we need to search also for !NEW

2021-11-18 08:27 UTC, andreyvEze commented on server/src/services/users/UpdateEmailRequest.mjs
> +    return ['data.id'];
let's hide `oldEmail` and `newEmail`

2021-11-18 08:29 UTC, andreyvEze commented on client/src/redux/profile/reducer.ts
> +            status: action.data.status,
I think we don't need to receive status and updatedEmail here, status should be set just to NON_VERIFIED and updatedEmail you can take from action

2021-11-18 08:29 UTC, andreyvEze commented on client/src/redux/profile/reducer.ts
> +          return { ...state, status: action.data.status };
here also just set the ACTIVE status, do not send status from server

2021-11-18 08:30 UTC, andreyvEze commented on client/src/redux/profile/reducer.ts
> +            status: action.data.status,
also here, just set ACTIVE

2021-11-18 08:30 UTC, andreyvEze commented on server/src/services/users/UpdateEmailRequest.mjs
> +    return { data: { status: user.status, updatedEmail: newEmail } };
just send `success: true` or something like this

2021-11-18 08:31 UTC, andreyvEze commented on server/src/services/users/UpdateEmailRevert.mjs
> +          id: ['required', 'string'],
remove, `this.context.id`

2021-11-18 08:32 UTC, andreyvEze commented on server/src/router.mjs
> +router.post('/users/updateEmail', routes.users.updateEmail);
add `checkAuth`

2021-11-18 08:33 UTC, andreyvEze commented on server/src/router.mjs
> +router.post('/users/updateEmailRequest', routes.users.updateEmailRequest);
add `checkAuth`

2021-11-18 08:33 UTC, andreyvEze commented on server/src/services/users/UpdateEmailRevert.mjs
> +    const action = await Action.findOneWhere({
move after user got

2021-11-18 08:34 UTC, andreyvEze commented on server/src/services/users/UpdateEmailRevert.mjs
> +    return { data: { status: user.status } };
just `success: true`

2021-11-18 08:34 UTC, andreyvEze commented on server/src/services/users/UpdateEmailRevert.mjs
> +    return ['data.id'];
empty array

2021-11-18 08:34 UTC, andreyvEze commented on server/src/services/users/UpdateEmailRevert.mjs
> +      where: { status: { [Op.ne]: User.STATUS.BLOCKED } },
check for NEW

2021-11-18 08:34 UTC, andreyvEze requested changes
see coments

2021-11-18 10:20 UTC, trukhilio commented on client/src/util/auth.ts
> +export const emailAvailable = async (
create middleware folder in api and move this file there

2021-11-18 10:34 UTC, trukhilio commented on client/src/util/hooks.ts
> +      return;
- change NON_VERIFIED to UPDATE_EMAIL_CONFIRM? everywhere
- rename selector isNonVerifiedUser to isNotUpdatedEmailConfirm everywhere
- rename route too
- create new selector isNewUser and use it instead of isNotActiveUser logic here
- private route changes required too

2021-11-18 10:46 UTC, trukhilio commented on server/src/services/users/UpdateEmailRequest.mjs
> +      where: { status: { [Op.ne]: User.STATUS.BLOCKED } },
check for status User.STATUS.ACTIVE

2021-11-18 10:48 UTC, trukhilio commented on server/src/services/users/UpdateEmailRevert.mjs
> +      where: { status: { [Op.ne]: User.STATUS.BLOCKED } },
check for User.STATUS.NON_VERIFIED

2021-11-18 19:42 UTC, andreyvEze commented on client/src/redux/profile/reducer.ts
> +            updatedEmail: action.updatedEmail,
newEmail

2021-11-18 19:55 UTC, andreyvEze commented on client/src/pages/SettingsPage/components/ChangeEmail/ChangeEmail.tsx
> +          submitAction={submit}
add `edgeAccountLogoutBefore={true}` prop

2021-11-18 19:58 UTC, andreyvEze commented on client/src/pages/UpdateEmailPage/UpdateEmailPage.tsx
> +        loadProfile();
makes no sense

2021-11-18 20:07 UTC, andreyvEze commented on client/src/redux/profile/reducer.ts
> -      case actions.UPDATE_EMAIL_FAILURE:
not sure we should remove this

2021-11-19 10:33 UTC, andreyvEze commented on server/src/services/users/UpdateEmailRevert.mjs
> +    user.update({ status: User.STATUS.ACTIVE });
await

2021-11-19 10:34 UTC, andreyvEze commented on server/src/services/users/UpdateEmailRevert.mjs
> +    if (!action) {
do not throw, just remove action if exist

2021-11-19 10:35 UTC, andreyvEze commented on server/src/services/users/UpdateEmailRequest.mjs
> +    user.update({ status: User.STATUS.HAS_EMAIL_TO_UPDATE });
await

2021-11-19 17:45 UTC, merged