BD-2550. Link tokens
fioprotocol/fio-dashboard pull request #387
Opened 2021-12-28 13:14 UTC by trukhilio

2021-12-28 13:55 UTC, andreyvEze commented on client/src/constants/common.ts
> +  TOKEN_LIST: 'TOKEN_LIST',
let's create const for each action - add/edit/delete

2021-12-28 13:56 UTC, andreyvEze commented on client/src/pages/AddTokenPage/AddTokenPage.tsx
> +      <ConfirmContainer
What is this for? could we use Results component?

2021-12-28 13:57 UTC, andreyvEze commented on client/src/pages/EditTokenPage/EditTokenPage.tsx
> +  // eslint-disable-next-line no-unused-vars
remove

2021-12-28 13:57 UTC, andreyvEze commented on client/src/pages/EditTokenPage/components/PublicAddressEdit.tsx
> +      size={editedPubAddress.length * 1.2} // makes width of input almost the same as text
should we create const for `1.2`?

2021-12-28 13:58 UTC, andreyvEze requested changes
check comments

2021-12-30 09:44 UTC, andreyvEze commented on client/src/api/fio.ts
> +      return await this.walletFioSDK.genericAction(action, params);
is it not catch an error without `await`?

2022-01-06 15:40 UTC, andreyvEze commented on client/src/api/fio.ts
> +  linkTokens = async (params: {
remove

2022-01-06 15:41 UTC, andreyvEze commented on client/src/components/Badges/TokenBadge/TokenBadge.module.scss
> +  .publicAddressItem {
should we name it in common way? not connected to business logic

2022-01-06 15:42 UTC, andreyvEze commented on client/src/components/Badges/TokenBadge/TokenBadge.module.scss
> +    .pubAddress {
same here, rename

2022-01-06 15:46 UTC, andreyvEze commented on client/src/components/LinkTokenList/constants.ts
> +  buttonText: 'Renew',
add bundled transactions not renew

2022-01-06 15:49 UTC, andreyvEze commented on client/src/pages/AddTokenPage/AddTokenPage.tsx
> +            containerName={CONTAINER_NAMES.ADD}
no need to set it here

2022-01-06 15:53 UTC, andreyvEze commented on client/src/pages/AddTokenPage/AddTokenPage.tsx
> +            remaining={remaining}
could we pass just `currentFioAddress` not every prop in it?

2022-01-06 15:58 UTC, andreyvEze commented on client/src/pages/AddTokenPage/index.ts
> +      getFioAddresses,
do we use it somewhere?

2022-01-06 16:05 UTC, andreyvEze commented on client/src/pages/EditTokenPage/EditTokenPage.tsx
> +            />
could we use final form here?

2022-01-06 16:06 UTC, andreyvEze commented on client/src/pages/EditTokenPage/EditTokenPage.tsx
> +        remaining={remaining}
rename to `remainingBundledTxs`

2022-01-06 16:08 UTC, andreyvEze commented on client/src/pages/LinkTokenPage/TokenListPage.tsx
> +import React, { useState, useEffect } from 'react';
rename file or folder

2022-01-06 16:12 UTC, andreyvEze commented on client/src/redux/fio/reducer.ts
> +  showTokenListInfoBadge(state: boolean = true, action) {
why do we need this?

2022-01-06 16:19 UTC, andreyvEze commented on client/src/pages/LinkTokenPage/TokenListPage.tsx
> +        publicAddresses[0].chainCode.toLowerCase() ===
fix this, now there is no FIO in the list

2022-01-06 16:25 UTC, andreyvEze commented on client/src/types.d.ts
> +  more?: boolean;
remove

2022-01-06 16:30 UTC, andreyvEze commented on client/src/pages/DeleteTokenPage/index.ts
> +    getFioAddresses,
remove

2022-01-06 18:35 UTC, andreyvEze commented on client/src/util/hooks.ts
> +    if (currentFioAddress.more) {
how `more` is could be here? please check and refactor (remove places where `more` could be set to fio addresses)

2022-01-06 18:44 UTC, merged

2022-01-10 13:06 UTC, trukhilio commented on client/src/pages/LinkTokenPage/TokenListPage.tsx
> +import React, { useState, useEffect } from 'react';
I don't have this folder, I have `TokenListPage/TokenListPage.tsx`