Add Stake ui
fioprotocol/fio-dashboard pull request #505
Opened 2022-03-07 15:20 UTC by NikolasStelmakh

2022-03-07 16:43 UTC, andreyvEze commented on client/src/components/Input/StakeAmountInput.tsx
> +        containerClassname={classes.badge}
I think we need to create common solution for it

2022-03-07 17:11 UTC, andreyvEze commented on client/src/components/Input/StakeAmountInput.tsx
> +    maxValueLabel = 'Available Staked FIO Balance: ',
let's set default value to `Available FIO Balance` and without `:`

2022-03-07 17:13 UTC, andreyvEze commented on client/src/components/Input/StakeAmountInput.tsx
> +            onChange={e => {
do we need this? could be removed

2022-03-07 17:43 UTC, andreyvEze commented on client/src/components/Input/StakeAmountInput.tsx
> +      {maxValue && (
do we have any case when it should not be shown?

2022-03-07 17:46 UTC, andreyvEze commented on client/src/components/common/TransactionResults/components/StakeTokensResults.tsx
> +import Amount from '../../Amount';
move to components imports

2022-03-07 17:46 UTC, andreyvEze commented on client/src/components/common/TransactionResults/components/StakeTokensResults.tsx
> +import { FIO_CHAIN_CODE } from '../../../../constants/fio';
move before type import

2022-03-07 17:46 UTC, andreyvEze commented on client/src/components/Input/StakeAmountInput.tsx
> +import { BADGE_TYPES } from '../Badge/Badge';
sort imports

2022-03-07 17:54 UTC, andreyvEze commented on client/src/pages/StakeTokensPage/components/StakeTokensForm/StakeTokensForm.tsx
> +          : Number(walletMaxAvailableAmount) - STAKE_MIN_VALUE_TO_SAVE + ''
MathOp

2022-03-07 17:54 UTC, andreyvEze commented on client/src/pages/StakeTokensPage/components/StakeTokensForm/StakeTokensForm.tsx
> +      apis.fio.sufToAmount(fioWallet.available || 0).toFixed(2),
use balances to set proper value

2022-03-07 17:56 UTC, andreyvEze commented on client/src/pages/StakeTokensPage/StakeTokensPage.tsx
> +import { useFioAddresses } from '../../util/hooks';
move before types

2022-03-07 18:07 UTC, andreyvEze commented on client/src/pages/StakeTokensPage/StakeTokensPage.tsx
> +    fioWallet && fioWallet.publicKey,
should be in the url

2022-03-07 18:53 UTC, andreyvEze commented on client/src/pages/StakeTokensPage/StakeTokensPage.tsx
> +    refreshWalletDataPublicKey(fioWallet.publicKey);
i think we don't need this

2022-03-07 18:59 UTC, andreyvEze commented on client/src/components/common/TransactionResults/components/StakeTokensResults.tsx
> +type TokenTransferResultsProps = ResultsProps & { roe: number; mapError?: any };
do we need `roe` here?

2022-03-07 18:59 UTC, andreyvEze commented on client/src/pages/StakeTokensPage/StakeTokensPage.tsx
> +        roe={roe}
do we need it here

2022-03-07 19:03 UTC, andreyvEze commented on client/src/pages/StakeTokensPage/components/StakeTokensForm/StakeTokensForm.tsx
> +import apis from '../../../../api';
please sort

2022-03-07 19:18 UTC, andreyvEze commented on client/src/pages/StakeTokensPage/components/StakeTokensForm/StakeTokensForm.tsx
> +            ? selectedAddress.remaining < BUNDLES_TX_COUNT.RECORD_OBT_DATA
please create STAKE option for BUNDLES_TX_COUNT

2022-03-07 19:24 UTC, andreyvEze commented on client/src/pages/StakeTokensPage/components/StakeTokensForm/StakeTokensForm.tsx
> +  ] = useState('0');
why do we need two values? `walletMaxAvailableAmount` | `walletMaxAllowedAvailableAmount`

2022-03-07 19:26 UTC, andreyvEze commented on client/src/pages/StakeTokensPage/components/StakeTokensForm/StakeTokensForm.tsx
> +  const renderFIOAddressInfoBadge = () => {
`renderFioAddressInfoBadge`

2022-03-07 19:27 UTC, andreyvEze commented on client/src/pages/StakeTokensPage/components/StakeTokensForm/StakeTokensForm.tsx
> +                  bundles={BUNDLES_TX_COUNT.RECORD_OBT_DATA}
proper option

2022-03-07 19:29 UTC, andreyvEze commented on client/src/pages/StakeTokensPage/index.ts
> +      state.fio.fees[apis.fio.actionEndPoints.transferTokens] ||
`apis.fio.actionEndPoints.stakeFioTokens`

2022-03-07 19:29 UTC, andreyvEze commented on client/src/pages/StakeTokensPage/index.ts
> +    getFee: () => getFee(apis.fio.actionEndPoints.transferTokens),
`apis.fio.actionEndPoints.stakeFioTokens`

2022-03-07 19:30 UTC, andreyvEze requested changes
see comments

2022-03-08 05:29 UTC, NikolasStelmakh commented on client/src/components/Input/StakeAmountInput.tsx
> +export const StakeAmountInput = (
in my opinion it's will be a bad idea: unnecessary 'if' checks will lower perfomance and moreover the code reading

2022-03-08 05:46 UTC, NikolasStelmakh commented on client/src/pages/StakeTokensPage/StakeTokensPage.tsx
> +    refreshWalletDataPublicKey(fioWallet.publicKey);
let's discuss

2022-03-08 06:11 UTC, NikolasStelmakh commented on client/src/pages/StakeTokensPage/components/StakeTokensForm/StakeTokensForm.tsx
> +  ] = useState('0');
For case, when there is no Fio crypto handle in the wallet: input should display max available FIO tokens, but prevent to use some amount; also submit button and lowBalanceBadge in form should be disabled when there is no **available - minimumTokensToSave** left. In input can be added default value equal to max available tokens to prevent unnecessary prop for unstake form

2022-03-08 07:34 UTC, andreyvEze commented on client/src/components/Badge/Badge.tsx
> +  if (!show) return null;
remove

2022-03-08 07:39 UTC, andreyvEze commented on client/src/components/InfoBadge/InfoBadge.tsx
> +    <Badge type={type} show={show} containerClassname={containerClassname}>
set {...rest} in which we will have `containerClassname` prop

2022-03-08 07:54 UTC, andreyvEze commented on client/src/components/Input/StakeAmountInput.tsx
> +    maxValue,
rename `available`

2022-03-08 07:54 UTC, andreyvEze commented on client/src/components/Input/StakeAmountInput.tsx
> +    maxAllowedValue,
`maxValue`

2022-03-08 12:30 UTC, andreyvEze commented on client/src/components/InfoBadge/InfoBadge.tsx
> +  className?: string;
let's import from Badge and join here

2022-03-08 12:32 UTC, andreyvEze commented on client/src/components/Input/StakeAmountInput.tsx
> +    maxValueTitle = 'Available Staked FIO Balance',
`Available FIO Balance`

2022-03-08 12:38 UTC, andreyvEze commented on client/src/components/Input/StakeAmountInput.tsx
> +    maxValueTitle = 'Available Staked FIO Balance',
availableTitle
```
    availableTitle = 'Available FIO Balance',
```

2022-03-08 12:40 UTC, andreyvEze commented on client/src/pages/StakeTokensPage/components/StakeTokensForm/StakeTokensForm.tsx
> +import { Label } from '../../../../components/Input/StaticInputParts';
move below `InfoBadge` import

2022-03-08 12:40 UTC, andreyvEze commented on client/src/pages/StakeTokensPage/components/StakeTokensForm/StakeTokensForm.tsx
> +import { ROUTES } from '../../../../constants/routes';
move below `BADGE_TYPES` import

2022-03-08 12:41 UTC, andreyvEze commented on client/src/pages/StakeTokensPage/components/StakeTokensForm/StakeTokensForm.tsx
> +import { ROUTES } from '../../../../constants/routes';
the same for `BUNDLES_TX_COUNT,  STAKE_MIN_VALUE_TO_SAVE,` import

2022-03-08 12:41 UTC, andreyvEze commented on client/src/pages/StakeTokensPage/components/StakeTokensForm/StakeTokensForm.tsx
> +import MathOp from '../../../../util/math';
move below `import { formValidation } from './validation';`

2022-03-08 12:44 UTC, andreyvEze commented on client/src/pages/StakeTokensPage/components/StakeTokensForm/StakeTokensForm.tsx
> +            STAKE_MIN_VALUE_TO_SAVE
use MathOp for calculations and comparations , not for type transformations

2022-03-08 12:44 UTC, andreyvEze commented on client/src/pages/StakeTokensPage/components/StakeTokensForm/StakeTokensForm.tsx
> +          new MathOp(amount).toNumber() > walletMaxAvailableAmount;
`new MathOp(amount).gt(walletMaxAvailableAmount);`

2022-03-08 12:46 UTC, andreyvEze commented on client/src/pages/StakeTokensPage/components/StakeTokensForm/StakeTokensForm.tsx
> +              availableValue={walletAvailableAmount}
remove `maxValueTitle` for this case

2022-03-08 12:48 UTC, andreyvEze requested changes
see comments

2022-03-08 14:22 UTC, andreyvEze commented on client/src/pages/StakeTokensPage/components/StakeTokensForm/StakeTokensForm.tsx
> +            new MathOp(walletAvailableAmount).toNumber(),
just `walletAvailableAmount`

2022-03-08 14:34 UTC, merged