Add Unstake Tokens Ui
fioprotocol/fio-dashboard pull request #514
Opened 2022-03-09 14:40 UTC by NikolasStelmakh

2022-03-09 15:38 UTC, andreyvEze commented on client/src/components/Input/StakeAmountInput.tsx
> +    maxValue = +availableValue,
maybe they should have the same type

2022-03-09 15:43 UTC, andreyvEze commented on client/src/components/common/TransactionResults/Results.tsx
> +            ) : null}
could we use `bottomElement` instead?

2022-03-09 15:43 UTC, andreyvEze commented on client/src/components/common/TransactionResults/components/StakeTokensResults.tsx
> +import InfoBadge from '../../../InfoBadge/InfoBadge';
move to components import

2022-03-09 15:50 UTC, andreyvEze commented on client/src/components/common/TransactionResults/types.d.ts
> +import SubmitButton from '../SubmitButton/SubmitButton';
move above types import

2022-03-09 15:51 UTC, andreyvEze commented on client/src/components/common/TransactionResults/types.d.ts
> +  additionalSubmitButtonProps?: SubmitButton;
we should set this props only for staking results component

2022-03-09 15:51 UTC, andreyvEze commented on client/src/pages/UnstakeTokensPage/UnstakeTokensPage.tsx
> +import { ResultsData } from '../../components/common/TransactionResults/types';
move to types import

2022-03-09 15:51 UTC, andreyvEze commented on client/src/pages/UnstakeTokensPage/UnstakeTokensPage.tsx
> +import { BADGE_TYPES } from '../../components/Badge/Badge';
move to const imports

2022-03-09 16:47 UTC, andreyvEze requested changes
check comments

2022-03-10 05:33 UTC, NikolasStelmakh commented on client/src/components/Input/StakeAmountInput.tsx
> +    maxValue = +availableValue,
it was in previous commits, but due to futher Number() manipulations in component it was refactored in fixup to different types

2022-03-10 07:21 UTC, merged