Update. DASH-107 Ref/Contained flow updates
fioprotocol/fio-dashboard pull request #621
Opened 2022-06-20 16:53 UTC by trukhilio

- Stay on the same page if no contained flow redirect parameter.

2022-06-23 07:29 UTC, andreyvEze commented on client/src/components/AddressDomainContainer/AddressDomainContainer.tsx
> +          {allowCustomDomains && !isContainedFlow && (
should it be setup from ref profile? why we hide it when contained flow?

2022-06-23 07:30 UTC, andreyvEze commented on client/src/components/AddressDomainContainer/AddressDomainContainer.tsx
> +          )}
also, should it affect somehow the widget?

2022-06-23 07:32 UTC, andreyvEze commented on client/src/components/CheckoutPurchaseContainer/CheckoutPurchaseContainer.tsx
> +      fioActionExecuted({
let's check if this should be called not only when !isRetry

2022-06-23 07:38 UTC, andreyvEze commented on client/src/components/EdgeConfirmAction/EdgeConfirmAction.tsx
> +            txIds: result?.transaction_id,
proposition: let's check `action` and call `fioActionExecuted` only when it was fio action

2022-06-23 07:39 UTC, andreyvEze commented on client/src/components/EdgeConfirmAction/EdgeConfirmAction.tsx
> +            result,
let's discuss result types and this method params type

2022-06-23 07:39 UTC, andreyvEze commented on client/src/components/PurchaseNow/middleware.ts
> +          domainTxId:
why we need to separate it?

2022-06-23 07:42 UTC, andreyvEze commented on client/src/components/SignNft/SignNft.tsx
> +  const initRes = JSON.stringify(initialResults);
need to discuss

2022-06-23 07:43 UTC, andreyvEze commented on client/src/components/SignNft/SignNft.tsx
> -
want to clarify why do we need this change

2022-06-23 07:48 UTC, andreyvEze commented on client/src/redux/containedFlow/sagas.ts
> +        );
let's discuss why we need to navigate here

2022-06-23 07:50 UTC, andreyvEze commented on client/src/redux/types.d.ts
> +  AnyType; // todo: check why do we need this here
we need to set proper types somtimes - all possible types I assume

2022-06-23 07:51 UTC, andreyvEze commented on client/src/services/ContainedFlow.tsx
> +export default withRouter(compose(reduxConnect)(ContainedFlow));
what is wrong with `useHistory`?

2022-06-23 07:53 UTC, andreyvEze commented on client/src/util/homePage.ts
> +        '';
if empty string it will set some other default title in the end?

2022-06-23 07:53 UTC, andreyvEze requested changes
review

2022-06-23 08:28 UTC, andreyvEze commented on client/src/components/AddressDomainContainer/AddressDomainContainer.tsx
> +          )}
could you please change `AddressDomainFrom` -> `AddressDomainForm`

2022-06-23 08:45 UTC, andreyvEze commented on client/src/components/EdgeConfirmAction/EdgeConfirmAction.tsx
> +            txIds: result?.transaction_id,
```
{
 result,
 data,
 executeActionType
}
```

2022-06-23 10:27 UTC, andreyvEze commented on client/src/components/SignNft/SignNft.tsx
> +  const initRes = JSON.stringify(initialResults);
assume it would be removed

2022-06-23 10:28 UTC, andreyvEze commented on client/src/redux/containedFlow/sagas.ts
> +        );
will be removed and created new saga for Results Close event

2022-06-23 10:31 UTC, andreyvEze commented on client/src/services/ContainedFlow.tsx
> +export default withRouter(compose(reduxConnect)(ContainedFlow));
let's turn it back for now, please update todo message

2022-07-01 09:33 UTC, andreyvEze commented on client/src/pages/FioAddressSignPage/FioAddressSignPage.tsx
> +  const params: { address?: string } = useParams();
why we need the hook if we could get params from props

2022-07-01 09:36 UTC, andreyvEze commented on client/src/pages/FioAddressSignPage/FioAddressSignPage.tsx
> +          containedFlowQueryParams
here we should check for `address`

2022-07-01 09:36 UTC, andreyvEze commented on client/src/pages/FioAddressSignPage/FioAddressSignPage.tsx
> +          containedFlowQueryParams
here we should check for `address`

2022-07-01 09:51 UTC, andreyvEze commented on client/src/constants/common.ts
> +export const FIO_ACTIONS = {
`CONFIRM_PIN_FIO_ACTIONS`

2022-07-01 09:55 UTC, andreyvEze commented on client/src/components/common/TransactionResults/Results.tsx
> +    setContainedFlowFinishStep();
do not use contained flow logic, here should be some event called like `txResultsClosed`

2022-07-01 09:58 UTC, andreyvEze commented on client/src/pages/PurchasePage/PurchasePage.tsx
> +      }
maybe would be cool if we do here the same as on resultsClose

2022-07-01 09:58 UTC, andreyvEze commented on client/src/redux/containedFlow/actions.ts
> +});
should be removed/moved to other actions

2022-07-01 10:00 UTC, andreyvEze commented on client/src/redux/containedFlow/sagas.ts
> +export function* finishContainedFlow(): Generator {
`resultsCloseContainedFlow`

2022-07-01 10:00 UTC, andreyvEze commented on client/src/redux/containedFlow/sagas.ts
> +  yield takeEvery(FINISH_CONTAINED_FLOW, function*() {
should be other name

2022-07-01 10:02 UTC, andreyvEze commented on client/src/services/ContainedFlow.tsx
> +          return setStep(CONTAINED_FLOW_STEPS.ACTION, { containedFlowAction });
```
return setStep(CONTAINED_FLOW_STEPS.ACTION, { initialValues: containedFlowAction });
```

2022-07-01 10:05 UTC, andreyvEze commented on client/src/pages/CheckoutPage/CheckoutPage.tsx
> +        (!paymentWalletPublicKey && fioWallets.length > 1))
discuss

2022-07-01 10:06 UTC, andreyvEze reviewed
check comments

2022-07-01 13:21 UTC, trukhilio commented on client/src/constants/common.ts
> +export const FIO_ACTIONS = {
done

2022-07-01 13:21 UTC, trukhilio commented on client/src/pages/FioAddressSignPage/FioAddressSignPage.tsx
> +          containedFlowQueryParams
done

2022-07-01 13:21 UTC, trukhilio commented on client/src/pages/FioAddressSignPage/FioAddressSignPage.tsx
> +      containedFlowQueryParams?: ContainedFlowQueryParams;
done

2022-07-01 13:21 UTC, trukhilio commented on client/src/pages/FioAddressSignPage/FioAddressSignPage.tsx
> +  const params: { address?: string } = useParams();
done

2022-07-01 13:53 UTC, trukhilio commented on client/src/redux/containedFlow/sagas.ts
> +export function* finishContainedFlow(): Generator {
done

2022-07-01 13:53 UTC, trukhilio commented on client/src/redux/containedFlow/sagas.ts
> +  yield takeEvery(FINISH_CONTAINED_FLOW, function*() {
done

2022-07-01 13:53 UTC, trukhilio commented on client/src/services/ContainedFlow.tsx
> +          return setStep(CONTAINED_FLOW_STEPS.ACTION, { containedFlowAction });
it should be as is, initial values are on the other place

2022-07-01 13:55 UTC, trukhilio commented on client/src/pages/EmailConfirmationResultsPage/EmailConfirmationResultsPage.tsx
> +  const history = useHistory();
done

2022-07-01 14:22 UTC, trukhilio commented on client/src/components/common/TransactionResults/Results.tsx
> +    setContainedFlowFinishStep();
done

2022-07-01 14:59 UTC, trukhilio commented on client/src/pages/PurchasePage/PurchasePage.tsx
> +      }
done

2022-07-04 08:13 UTC, andreyvEze commented on client/src/pages/FioAddressSignPage/FioAddressSignPage.tsx
> +    location: { state },
is it there? just to confirm

2022-07-04 08:13 UTC, andreyvEze commented on client/src/pages/FioAddressSignPage/FioAddressSignPage.tsx
> +          !address
could we change the order:
```
address ? putParamsToUrl(ROUTES.FIO_ADDRESS_SIGNATURES, { address }) : null
```

2022-07-04 08:14 UTC, andreyvEze commented on client/src/pages/PurchasePage/PurchasePage.tsx
> +    onPurchaseResultsClose();
👍

2022-07-04 08:15 UTC, andreyvEze commented on client/src/redux/registrations/sagas.ts
> +export function* purchaseResultsClose(history: History): Generator {
move this saga to contained flow sagas

2022-07-04 08:18 UTC, andreyvEze requested changes
please change last comments

2022-07-04 08:32 UTC, trukhilio commented on client/src/pages/FioAddressSignPage/FioAddressSignPage.tsx
> +          !address
Done

2022-07-04 08:57 UTC, merged