DASH-149. Add before submit payment logis, sign tx for private domains
fioprotocol/fio-dashboard pull request #675
Opened 2022-08-12 12:15 UTC by andreyvEze

2022-08-12 17:32 UTC, NikolasStelmakh commented on client/src/components/EdgeConfirmAction/EdgeConfirmAction.tsx
> +            allKeys: fioWalletEdgeId ? null : keys,
maybe could be renamed, because meaning is not clear (the difference from keys)

2022-08-12 17:52 UTC, NikolasStelmakh commented on client/src/pages/CheckoutPage/components/BeforeSubmitEdgeWallet.tsx
> +        throw err;
mb use logger.error

2022-08-18 13:50 UTC, trukhilio requested changes
Check comments

2022-08-18 13:50 UTC, trukhilio commented on client/src/pages/CheckoutPage/components/BeforeSubmitEdgeWallet.tsx
> +    for (const item of data.fioAddressItems) {
Could we rename `item` to `fioAddressItem`?

2022-08-18 13:50 UTC, trukhilio commented on client/src/pages/CheckoutPage/components/StripeForm.tsx
> +import { BeforeSubmitData } from '../types';
Please, move types above `classes`

2022-08-18 13:50 UTC, trukhilio commented on server/src/jobs/orders.mjs
> +    // todo:
Please, type what we need to do here

2022-08-18 13:50 UTC, trukhilio commented on server/src/jobs/orders.mjs
> +  async submitSignedTx(item, balanceDifferance = null) {
Could we rename `item` into `order`?

2022-08-18 13:50 UTC, trukhilio commented on server/src/jobs/orders.mjs
> +      if (notes === INSUFFICIENT_FUNDS_ERR_MESSAGE && !balanceDifferance) {
typo in `balanceDifferance`, I assume it should be `balanceDifference`

2022-08-18 13:50 UTC, trukhilio commented on server/src/jobs/tx-check.mjs
> +    const processTxItem = item => async () => {
What's the pros of this function declaration?

2022-08-18 13:50 UTC, trukhilio commented on server/src/services/orders/Create.mjs
> +            data: itemData ? { ...itemData } : null,
Could we set `itemData || null` here?

2022-08-18 15:02 UTC, trukhilio approved these changes

2022-08-18 15:02 UTC, merged