DASH-31 Add search admin logic
fioprotocol/fio-dashboard pull request #687
Opened 2022-08-23 13:23 UTC by NikolasStelmakh

2022-08-23 13:42 UTC, andreyvEze commented on server/src/services/adminUsers/Search.mjs
> +  return email.match(
there should be option in the current validation, please check and use it

2022-08-24 13:41 UTC, andreyvEze commented on client/src/components/MainHeader/components/AdminSearch.tsx
> +      {isAdmin ? (
could we move it to `LoggedActionButtons` component ?

2022-08-24 13:46 UTC, andreyvEze commented on server/src/services/adminUsers/Search.mjs
> +      // could be useful in future
create in this class `userSearch method and move all this commented logic there`

2022-08-24 13:46 UTC, andreyvEze requested changes
check comments

2022-08-24 14:47 UTC, NikolasStelmakh commented on client/src/components/MainHeader/components/AdminSearch.tsx
> +      {isAdmin ? (
why?)

2022-08-24 15:09 UTC, merged