DASH-187 Edit Admin User Modal
fioprotocol/fio-dashboard pull request #721
Opened 2022-09-08 13:07 UTC by vmkarpenko

2022-09-11 22:41 UTC, NikolasStelmakh approved these changes

2022-09-14 09:45 UTC, trukhilio requested changes
Check comments

2022-09-14 09:45 UTC, trukhilio commented on client/src/pages/AdminPasswordResetPage/AdminPasswordResetPage.tsx
> +    }).then(res => {
Could we use async await here? What is the reason to use `then` method here?

2022-09-14 09:45 UTC, trukhilio commented on client/src/pages/AdminPasswordResetPage/AdminPasswordResetPage.tsx
> +      {isTokenValidationLoading ? (
Let's refactor this html and make something like:
```
if (isTokenValidationLoading) return <Loader />
if (tokenValidationError) return (
   <div>
         <p>Token is not valid!</p>
         <p>{tokenValidationError?.code}</p>
   </div>
)
  return <AdminPasswordResetForm
              onSubmit={onSubmit}
              loading={loading}
              initialValues={initialValues}
            />
```
 `

2022-09-14 09:45 UTC, trukhilio commented on client/src/pages/AdminPasswordResetPage/components/AdminPasswordResetForm/index.ts
> +import AdminPasswordResetForm from './AdminPasswordResetForm';
Let's make `export * from './AdminPasswordResetForm';` instead of `import/export`

2022-09-14 09:45 UTC, trukhilio commented on client/src/pages/AdminPasswordResetPage/index.ts
> +import { connect } from 'react-redux';
We could move redux selectors and component's logic into `AdminPasswordResetPageContext` file. And return only data for render components.
You could look as an example `CheckoutPage` components

2022-09-14 09:45 UTC, trukhilio commented on client/src/pages/AdminUserListPage/AdminUserListPage.tsx
> +  const {
We also could move logic here into `AdminPasswordResetPageContext` file

2022-09-14 09:45 UTC, trukhilio commented on server/src/models/Action.mjs
> +      RESET_ADMIN_PASSWORD: 'resetAdminEmail',
Could you rename `resetAdminEmail` to `resetAdminPasswordEmail`?

2022-09-14 09:45 UTC, trukhilio commented on client/src/api/admin.ts
> +  checkIsAdminPasswordResetCorrect({
I think it's better to rename `checkIsAdminPasswordResetCorrect` into `checkIsAdminPasswordResetSuccess`

2022-09-14 13:25 UTC, trukhilio approved these changes

2022-09-14 13:26 UTC, merged