DASH-163 DASH-147 Add page titles and update url/params
fioprotocol/fio-dashboard pull request #748
Opened 2022-09-16 15:07 UTC by vmkarpenko

2022-09-19 10:01 UTC, andreyvEze commented on client/src/components/AuthContainer/AuthContainer.tsx
> +      {location.pathname !== ROUTES.CREATE_ACCOUNT && <Redirect to="/404" />}
let's update `/404` to `ROUTES.NOT_FOUND`

2022-09-19 10:02 UTC, andreyvEze commented on client/src/components/CreateAccountForm/CreateAccountForm.tsx
> +import PageTitle from '../PageTitle/PageTitle';
please move imports to relevant sections - components, const, utl, types

2022-09-19 10:12 UTC, andreyvEze commented on client/src/components/PageTitle/PageTitle.tsx
> +  }, [link, title]);
confirm there are no cases it would fire 2 or more times

2022-09-19 10:14 UTC, andreyvEze commented on client/src/pages/RefHomePage/RefHomePage.tsx
> +  }, [refProfileInfo]);
better to avoid using objects in dependencies array, let's refactor to be as `[refProfileInfo.code, refProfileInfo.label]`

2022-09-19 10:18 UTC, andreyvEze commented on client/src/pages/RefHomePage/RefHomePage.tsx
> +            <title>FIO Dashboard - {refProfileInfo.label}</title>
do we have a const for this? `FIO Dashboard`

2022-09-19 10:21 UTC, andreyvEze commented on client/src/components/PasswordRecoveryForm/PasswordRecoveryForm.tsx
> +import { LINKS } from '../../constants/labels';
sort

2022-09-19 10:23 UTC, andreyvEze commented on client/src/components/FioNameRenew/FioNameRenewContainer.tsx
> +} from '../../constants/labels';
sort

2022-09-19 10:33 UTC, andreyvEze commented on client/src/components/FioNameRenew/FioNameRenewContainer.tsx
> +      <PageTitle link={RENEW_PAGE_LINK[fioNameType]} />
should we add PageTitle above in the `error` case?

2022-09-19 10:34 UTC, andreyvEze commented on client/src/components/FioNameTransfer/FioNameTransferContainer.tsx
> +import PageTitle from '../PageTitle/PageTitle';
move to the components imports

2022-09-19 10:35 UTC, andreyvEze commented on client/src/components/LinkTokenList/ActionContainer.tsx
> +import { LINKS } from '../../constants/labels';
sort

2022-09-19 10:35 UTC, andreyvEze commented on client/src/components/LoginForm/LoginForm.tsx
> +import { LINKS } from '../../constants/labels';
sort

2022-09-19 10:36 UTC, andreyvEze commented on client/src/components/ManagePageContainer/ManagePageComponents/SettingsItem.tsx
> +import { FIO_OWNERSHIP, SETTING_LINK } from '../constants';
sort

2022-09-19 10:38 UTC, andreyvEze commented on client/src/components/ManagePageContainer/constants.tsx
> +import { LINKS } from '../../constants/labels';
sort

2022-09-19 10:38 UTC, andreyvEze commented on client/src/components/Modal/GenericErrorModal/GenericErrorModal.tsx
> +import { LINKS } from '../../../constants/labels';
sort

2022-09-19 10:39 UTC, andreyvEze commented on client/src/components/SignNft/SignNft.tsx
> +import { LINKS } from '../../constants/labels';
sort

2022-09-19 10:43 UTC, andreyvEze commented on client/src/constants/routes.ts
> +  IMPORT_WALLET: '/import',
do we need to change IMPORT_WALLET url?

2022-09-19 10:44 UTC, andreyvEze commented on client/src/pages/AddTokenPage/AddTokenPage.tsx
> +import { LINKS } from '../../constants/labels';
sort

2022-09-19 10:46 UTC, andreyvEze commented on client/src/pages/CartPage/CartPage.tsx
> +import { LINKS } from '../../constants/labels';
sort

2022-09-19 10:47 UTC, andreyvEze commented on client/src/pages/CheckoutPage/CheckoutPage.tsx
> +import { LINKS } from '../../constants/labels';
sort

2022-09-19 10:47 UTC, andreyvEze commented on client/src/pages/CookieNoticePage/CookieNoticePage.tsx
> +import { LINKS } from '../../constants/labels';
empty line above

2022-09-19 10:47 UTC, andreyvEze commented on client/src/pages/DashboardPage/DashboardPage.tsx
> +import { LINKS } from '../../constants/labels';
empty line above

2022-09-19 10:48 UTC, andreyvEze commented on client/src/pages/EmailConfirmGatePage/EmailConfirmGate.tsx
> +import { LINKS } from '../../constants/labels';
empty line

2022-09-19 10:48 UTC, andreyvEze commented on client/src/pages/EmailConfirmGatePage/EmailConfirmGate.tsx
> +    <PageTitle link={LINKS.IS_NEW_USER} />
need to discuss

2022-09-19 10:49 UTC, andreyvEze commented on client/src/pages/FioAddressAddBundlesPage/FioAddressAddBundlesPage.tsx
> +import { LINKS } from '../../constants/labels';
sort

2022-09-19 10:57 UTC, andreyvEze commented on client/src/pages/FioAddressManagePage/FioAddressManagePage.tsx
> +import { LINKS } from '../../constants/labels';
sort

2022-09-19 10:58 UTC, andreyvEze commented on client/src/pages/FioAddressSignaturesPage/FioAddressSignaturesPage.tsx
> +import { LINKS } from '../../constants/labels';
sort

2022-09-19 10:59 UTC, andreyvEze commented on client/src/pages/FioDomainPage/FioDomainPage.tsx
> +    </>
@trukhilio should we rename these files? to FioDomainSelectionPage or something

2022-09-19 11:00 UTC, andreyvEze commented on client/src/pages/FioDomainStatusChangePage/FioDomainStatusChangePage.tsx
> +import { LINKS } from '../../constants/labels';
sort

2022-09-19 11:01 UTC, andreyvEze commented on client/src/pages/FioTokensRequestPage/FioTokensRequestPage.tsx
> +import { LINKS } from '../../constants/labels';
empty line

2022-09-19 11:02 UTC, vmkarpenko commented on client/src/components/PageTitle/PageTitle.tsx
> +  }, [link, title]);
title it’s a string from constant that equal to some link. it will fire only by link change

2022-09-19 11:02 UTC, andreyvEze commented on client/src/pages/FioTokensRequestPage/FioTokensRequestPage.tsx
> +      query: { publicKey: publicKeyFromPath } = {},
check how page would work without query params

2022-09-19 11:03 UTC, andreyvEze commented on client/src/pages/HomePage/HomePage.tsx
> +import { LINKS } from '../../constants/labels';
sort

2022-09-19 11:04 UTC, andreyvEze commented on client/src/pages/HomePage/HomePage.tsx
> +      history.replace(ROUTES.DASHBOARD);
let's discuss

2022-09-19 11:05 UTC, andreyvEze commented on client/src/pages/NotFoundPage/NotFoundPage.tsx
> +import { LINKS } from '../../constants/labels';
empty line

2022-09-19 11:05 UTC, andreyvEze commented on client/src/pages/PrivacyPolicyPage/PrivacyPolicyPage.tsx
> +import { ROUTES } from '../../constants/routes';
empty line

2022-09-19 11:05 UTC, andreyvEze commented on client/src/pages/PurchasePage/PurchasePage.tsx
> +import { LINKS } from '../../constants/labels';
sort

2022-09-19 11:06 UTC, andreyvEze commented on client/src/pages/RejectFioRequestPage/RejectFioRequestPage.tsx
> +import { LINKS } from '../../constants/labels';
sort

2022-09-19 11:07 UTC, andreyvEze commented on client/src/pages/SendPage/SendPage.tsx
> +import { LINKS } from '../../constants/labels';
empty line

2022-09-19 11:08 UTC, andreyvEze commented on client/src/pages/SendPage/index.ts
> +          publicKey === ownProps.location.query.publicKey,
I think we need to check for location.query existence

2022-09-19 11:08 UTC, andreyvEze commented on client/src/pages/SettingsPage/SettingsPage.tsx
> +import { LINKS } from '../../constants/labels';
sort

2022-09-19 11:08 UTC, vmkarpenko commented on client/src/components/FioNameRenew/FioNameRenewContainer.tsx
> +      <PageTitle link={RENEW_PAGE_LINK[fioNameType]} />
It was listed in requirements and this component will fire required event too

2022-09-19 11:08 UTC, andreyvEze commented on client/src/pages/StakeTokensPage/StakeTokensPage.tsx
> +import { LINKS } from '../../constants/labels';
sort

2022-09-19 11:09 UTC, andreyvEze commented on client/src/pages/TermsOfServicePage/TermsOfServicePage.tsx
> +import { LINKS } from '../../constants/labels';
sort

2022-09-19 11:10 UTC, vmkarpenko commented on client/src/components/FioNameRenew/FioNameRenewContainer.tsx
> +      <PageTitle link={RENEW_PAGE_LINK[fioNameType]} />
there wasn't requirement for this, only for confirmation page. do you think for error case there is should be separate title and event fired?

2022-09-19 11:12 UTC, vmkarpenko commented on client/src/components/Badges/TokenBadge/NFTTokenBadge.tsx
> -import { putParamsToUrl } from '../../../utils';
it really isn't used anywhere else and can be removed. will do

2022-09-19 11:14 UTC, andreyvEze requested changes
check comments

2022-09-19 11:14 UTC, andreyvEze commented on client/src/pages/TokenListPage/TokenListPage.tsx
> +import { LINKS } from '../../constants/labels';
sort

2022-09-19 11:14 UTC, andreyvEze commented on client/src/pages/TokenListPage/TokenListPage.tsx
> +            search={search}
check

2022-09-19 11:14 UTC, andreyvEze commented on client/src/pages/TokensRequestPaymentPage/PaymentDetailsPage.tsx
> +import { LINKS } from '../../constants/labels';
sort

2022-09-19 11:14 UTC, andreyvEze commented on client/src/pages/UnstakeTokensPage/UnstakeTokensPage.tsx
> +import { LINKS } from '../../constants/labels';
sort

2022-09-19 11:14 UTC, andreyvEze commented on client/src/pages/UnstakeTokensPage/index.ts
> +          publicKey === ownProps.location.query.publicKey,
I think we need to check for existence

2022-09-19 11:14 UTC, andreyvEze commented on client/src/pages/WalletPage/WalletPage.tsx
> +import { LINKS } from '../../constants/labels';
sort

2022-09-19 11:14 UTC, andreyvEze commented on client/src/pages/WalletPage/components/WalletDetailsModal.tsx
> +import { LINKS } from '../../../constants/labels';
empty line

2022-09-19 11:14 UTC, andreyvEze commented on client/src/pages/WalletPage/index.ts
> +          publicKey === ownProps.location.query.publicKey,
check

2022-09-19 11:14 UTC, andreyvEze commented on client/src/pages/WalletsPage/WalletsPage.tsx
> +import { LINKS } from '../../constants/labels';
sort

2022-09-19 11:14 UTC, andreyvEze commented on server/src/services/emailSender.mjs
> +        let link = `${sendData.mainUrl}confirm-email?hash=${sendData.hash}`;
so sent links would not work

2022-09-19 11:14 UTC, andreyvEze commented on server/src/services/emailSender.mjs
> +            link: `${sendData.mainUrl}fio-wallet?publicKey=${sendData.wallet}`,
maybe we need to create some redirect on client side

2022-09-19 11:37 UTC, andreyvEze commented on client/src/pages/FioDomainPage/FioDomainPage.tsx
> +    </>
please decide in which PR you want to change it, maybe later in other task

2022-09-19 12:56 UTC, vmkarpenko commented on client/src/pages/FioTokensRequestPage/FioTokensRequestPage.tsx
> +      query: { publicKey: publicKeyFromPath } = {},
for this case it's allowed to use this page without parameters

2022-09-19 13:26 UTC, trukhilio requested changes
Check comments

2022-09-19 13:26 UTC, trukhilio commented on client/src/pages/FioTokensRequestPage/FioTokensRequestPage.tsx
> +        {publicKeyFromPath != null && publicKeyFromPath !== '' ? (
Let's create 
```
const isValidPublicKeyFromPath = publicKeyFromPath != null && publicKeyFromPath !== ''
``` 
and reuse it everywhere inside component

2022-09-19 13:26 UTC, trukhilio commented on client/src/pages/WalletPage/WalletPage.tsx
> +  const { location }: LocationProps = useHistory();
Let's get location from one entry point: from props or from useHistory

2022-09-19 13:26 UTC, trukhilio commented on client/src/pages/StakeTokensPage/index.ts
> +          publicKey === ownProps.location.query.publicKey,
Let's check for existence too

2022-09-19 13:26 UTC, trukhilio commented on client/src/pages/WalletPage/types.d.ts
> +      isOpenLockedList: boolean;
Check if this parameter is not optional

2022-09-19 13:33 UTC, vmkarpenko commented on client/src/pages/AdminPasswordResetPage/types.d.ts
> +type LocationProps = {
It's new functionality related to DASH-187

2022-09-19 13:34 UTC, andreyvEze commented on client/src/components/LoginForm/LoginForm.tsx
> +import { LINKS } from '../../constants/labels';
missed

2022-09-19 13:34 UTC, trukhilio commented on client/src/pages/AdminPasswordResetPage/types.d.ts
> +type LocationProps = {
ok

2022-09-19 13:39 UTC, vmkarpenko commented on client/src/pages/WalletPage/types.d.ts
> +      isOpenLockedList: boolean;
yes, it's optional

2022-09-19 15:32 UTC, andreyvEze commented on client/src/constants/routes.ts
> +  FIO_REQUEST_DECRYPT: '/new-request-confirmation-email',
let's rename the key `NEW-REQUEST-CONFIRM-EMAIL`

2022-09-19 15:32 UTC, andreyvEze commented on server/src/services/emailSender.mjs
> +            link: `${sendData.mainUrl}new-request-confirmation-email?publicKey=${sendData.wallet}&fioRequestId=${sendData.fioRequestId}`,
need to discuss the name

2022-09-19 18:05 UTC, trukhilio requested changes
Check comments

2022-09-19 18:05 UTC, trukhilio commented on client/src/components/AuthContainer/AuthContainer.tsx
> +      <Switch>
Let's do something like that:
```
if (isAuthenticated && !loading) return <Redirect to={ROUTES.HOME} />;
if (location.pathname !== ROUTES.CREATE_ACCOUNT) return <Redirect to={ROUTES.NOT_FOUND} />;

const renderAuthContent = () => {
 if (loading || !edgeContextSet) return <FontAwesomeIcon icon={faSpinner} spin className={styles.spinner} />;
if (!isAuthenticated && edgeContextSet) return (
<Switch>
 <Route path={ROUTES.CREATE_ACCOUNT} component={CreateAccount} exact />
</Switch>);
};
return (
 <div className={styles.container}>{renderAuthContent()}</div>
)
```
Check if it works as expected

2022-09-20 08:02 UTC, andreyvEze approved these changes

2022-09-20 09:12 UTC, trukhilio requested changes
Check comments

2022-09-20 09:12 UTC, trukhilio commented on client/src/pages/FioTokensRequestPage/FioTokensRequestPage.tsx
>  import { FioWalletDoublet, MappedPublicAddresses } from '../../types';
Please, move all types imports to the bottom of the import's block but under style import

2022-09-20 09:12 UTC, trukhilio commented on client/src/pages/MainLayout/MainLayout.tsx
>  import classes from './MainLayout.module.scss';
Move style imports to the bottom

2022-09-20 09:45 UTC, trukhilio approved these changes

2022-09-20 09:45 UTC, merged