DASH-161: Add custom analytics events
fioprotocol/fio-dashboard pull request #751
Opened 2022-09-20 12:27 UTC by vmkarpenko

2022-09-20 12:38 UTC, andreyvEze commented on client/src/components/EdgeConfirmAction/EdgeConfirmAction.tsx
> +          fireAnalyticsEvent('chain_error');
we need to check for `action` and fire it when it is one of `FioActions`

2022-09-20 15:00 UTC, andreyvEze commented on client/src/components/AddressDomainForm/validation.ts
> +        fireAnalyticsEvent('search', { search_term: 'fch', type: 'combo' });
just to confirm about `combo`

2022-09-20 15:17 UTC, andreyvEze commented on client/src/components/EdgeConfirmAction/EdgeConfirmAction.tsx
> +          fireAnalyticsEvent('chain_error');
also, I think we should move all events that related to fio actions to be called in sagas after `fioActionExecuted`

2022-09-20 15:19 UTC, andreyvEze commented on client/src/components/MainHeader/components/RegularNav.tsx
> +      'begin_checkout',
is it ok to move it to the checkout page / cart page?

2022-09-20 15:21 UTC, andreyvEze commented on client/src/pages/CheckoutPage/CheckoutPageContext.tsx
> +      'purchase_started',
should be moved from this place

2022-09-20 15:24 UTC, andreyvEze commented on client/src/redux/fio/sagas.ts
> +    fireAnalyticsEvent('wallet_create', { wallet_create_type: from });
is it work for ledger wallets?

2022-09-21 07:31 UTC, andreyvEze commented on client/src/components/PasswordRecoveryForm/PasswordRecoveryForm.tsx
> +      fireAnalyticsEvent('sec_recovery');
check how it can be moved to the edgeConfirmAction

2022-09-21 07:41 UTC, andreyvEze commented on client/src/pages/CheckoutPage/CheckoutPageContext.tsx
> +      transaction_id: order.id,
order number

2022-09-21 07:43 UTC, andreyvEze commented on client/src/pages/CheckoutPage/CheckoutPageContext.tsx
> +    }
move to PurchasePage

2022-09-21 08:30 UTC, trukhilio requested changes
Check comments

2022-09-21 08:30 UTC, trukhilio commented on client/src/pages/CheckoutPage/CheckoutPageContext.tsx
> +      fireAnalyticsEvent('purchase_partial');
Do we need to pass data in this case?

2022-09-21 08:30 UTC, trukhilio commented on client/src/pages/NftValidationPage/NftValidationPage.tsx
>        2000,
I'd like to ask you to move 2000 to constant

2022-09-21 08:30 UTC, trukhilio commented on client/src/pages/UnstakeTokensPage/UnstakeTokensPage.tsx
> +import { fireAnalyticsEvent } from '../../utils';
Move above classes

2022-09-21 08:30 UTC, trukhilio commented on client/src/utils.ts
> +    value: +cartItems.reduce((sum, item) => sum + +item.costUsdc, 0),
It's better to use `MathOp` util for sum because of big or decimal numbers

2022-09-21 08:30 UTC, trukhilio commented on client/src/utils.ts
> +    currency: 'USD',
We have a constant for USD currency

2022-09-21 08:30 UTC, trukhilio commented on client/src/components/AddressDomainForm/validation.ts
> +        fireAnalyticsEvent('search', { search_term: 'fch', type: 'combo' });
Let's move `search_term` and `type` values to constants also

2022-09-21 11:20 UTC, andreyvEze commented on client/src/pages/NftValidationPage/NftValidationPage.tsx
>        2000,
this is not new code, and not connected to the tast, we could skip it for now

2022-09-21 11:22 UTC, andreyvEze commented on client/src/pages/CheckoutPage/CheckoutPageContext.tsx
> +      fireAnalyticsEvent('purchase_partial');
no

2022-09-21 15:48 UTC, trukhilio requested changes

2022-09-21 15:48 UTC, trukhilio commented on client/src/components/MainHeader/components/LoggedNav.tsx
> +        'begin_checkout',
This also move to constants

2022-09-21 15:48 UTC, trukhilio commented on client/src/components/MainHeader/components/RegularNav.tsx
> +        'begin_checkout',
Also move to constants

2022-09-21 15:48 UTC, trukhilio commented on client/src/redux/edge/actions.ts
> +      method: pin ? 'pin' : 'password',
Let's move `pin` and `password` to constants too

2022-09-21 15:48 UTC, trukhilio commented on client/src/pages/RefHomePage/RefHomePage.tsx
> +import { ANALYTICS_EVENT_ACTIONS } from '../../constants/common';
Move above classes

2022-09-21 15:48 UTC, trukhilio commented on client/src/utils.ts
> +      result.token_send_type = data.to ? 'fch' : 'pubadd';
Please, use `fch`, `pubadd`, `ledger` and `standard` from constants

2022-09-21 15:48 UTC, trukhilio commented on client/src/utils.ts
> +        additionalData?.fioNameType === 'domain'
We have constant for `domain` fio type

2022-09-21 19:46 UTC, trukhilio approved these changes

2022-09-22 07:20 UTC, andreyvEze commented on client/src/components/LedgerConnect/LedgerConnect.tsx
> +      if (CONFIRM_LEDGER_ACTIONS[action as keyof LedgerActions]) {
for now it should be only `SEND`

2022-09-22 07:22 UTC, andreyvEze commented on client/src/pages/RefHomePage/RefHomePage.tsx
> +import { ANALYTICS_EVENT_ACTIONS } from '../../constants/common';
was it moved?

2022-09-22 07:25 UTC, andreyvEze commented on client/src/utils.ts
> +};
should we move analytics methods to `util/analytics.ts` ?

2022-09-22 07:26 UTC, andreyvEze commented on client/src/utils.ts
> +    if (action === CONFIRM_PIN_FIO_ACTIONS.SEND && additionalData.bundleSets) {
need to discuss

2022-09-22 08:09 UTC, andreyvEze approved these changes

2022-09-22 08:09 UTC, merged