DASH-131 Implement additional Ledger Actions
fioprotocol/fio-dashboard pull request #802
Opened 2022-10-18 20:13 UTC by vmkarpenko

2022-10-20 13:05 UTC, NikolasStelmakh approved these changes

2022-10-21 15:11 UTC, trukhilio requested changes
Check comments

2022-10-21 15:11 UTC, trukhilio commented on client/src/pages/FioAddressAddBundlesPage/components/AddBundlesLedgerWallet.tsx
> +        tpid: '',
Same tpid here

2022-10-21 15:11 UTC, trukhilio commented on client/src/pages/FioDomainStatusChangePage/components/FioDomainStatusLedgerWallet.tsx
> +        tpid: '',
Same tpid here

2022-10-21 15:11 UTC, trukhilio commented on client/src/pages/FioTokensRequestPage/components/RequestTokensLedgerWallet.tsx
> +        tpid: '',
Same tpid here

2022-10-21 15:11 UTC, trukhilio commented on client/src/pages/RejectFioRequestPage/components/RejectRequestLedger.tsx
> +          tpid: '',
Same tpid here

2022-10-21 15:11 UTC, trukhilio commented on client/src/pages/SendPage/components/SendLedgerWallet.tsx
> +        tpid: '',
Same tpid here

2022-10-21 15:11 UTC, trukhilio commented on client/src/pages/SendPage/components/SendLedgerWallet.tsx
> +            tpid: '',
Same tpid here

2022-10-21 15:11 UTC, trukhilio commented on client/src/pages/TokensRequestPaymentPage/components/PaymentDetailsLedgerWallet.tsx
> +        tpid: '',
Same tpid here

2022-10-21 15:11 UTC, trukhilio commented on client/src/pages/UnstakeTokensPage/components/UnstakeTokensLedgerWallet.tsx
> +        tpid: '',
Same tpid here

2023-01-12 10:03 UTC, trukhilio approved these changes

2024-03-21 11:26 UTC, merged