DASH-190 Add Item Descriptors
fioprotocol/fio-dashboard pull request #818
Opened 2022-10-28 14:36 UTC by vmkarpenko

2022-10-28 17:05 UTC, NikolasStelmakh approved these changes

2022-11-01 17:41 UTC, trukhilio requested changes
Check comments

2022-11-01 17:41 UTC, trukhilio commented on client/src/components/Cart/CartItem.tsx
> +import { getCartItemDescriptor } from '../../util/cart';
Please, move above `types` import

2022-11-01 17:41 UTC, trukhilio commented on client/src/components/ManagePageContainer/ManagePageComponents/ActionButtons.tsx
> +        onClick={handleAddBundles}
Could we use the same style as for `onRenewDomain` or vice versa?

2022-11-01 17:41 UTC, trukhilio commented on client/src/components/ManagePageContainer/ManagePageContainer.tsx
> +import { FIO_ADDRESS_DELIMITER } from '../../utils';
Move to `utils` import block

2022-11-01 17:41 UTC, trukhilio commented on client/src/components/PurchaseNow/middleware.ts
> +import { ACTIONS } from '../../constants/fio';
Move to constants import block

2022-11-01 17:41 UTC, trukhilio commented on client/src/util/cart.ts
> +            ? ACTIONS.renewFioDomain
Let's move it to function and return what we need. It's hard to read and if we will add more types and actions that would make a mess.

2022-11-01 17:41 UTC, trukhilio commented on server/src/external/fio.mjs
> +          bundle_sets: 1,
Let's move `1` to constant

2022-11-01 17:41 UTC, trukhilio commented on server/src/models/Order.mjs
> +        action === FIO_ACTIONS.renewFioDomain
Let's also move it to function

2022-11-02 09:55 UTC, vmkarpenko commented on client/src/components/ManagePageContainer/ManagePageContainer.tsx
> +import { FIO_ADDRESS_DELIMITER } from '../../utils';
but that is constant

2022-11-02 10:06 UTC, trukhilio commented on client/src/components/ManagePageContainer/ManagePageContainer.tsx
> +import { FIO_ADDRESS_DELIMITER } from '../../utils';
Oh, sure! Thanks

2022-11-02 16:12 UTC, trukhilio commented on client/src/util/cart.ts
> +  return type === CART_ITEM_TYPE.DOMAIN_RENEWAL
Let use if condition instead of ternary

2022-11-02 16:14 UTC, trukhilio commented on server/src/models/Order.mjs
> +    return action === FIO_ACTIONS.renewFioDomain
Let's also use `if` and `return` value here too

2022-11-02 17:03 UTC, merged