DASH-483: Implement Admin changes to support shopping design changes
fioprotocol/fio-dashboard pull request #955
Opened 2023-01-13 08:08 UTC by orkhan-huseyn

2023-01-17 11:24 UTC, trukhilio requested changes
Check comments

2023-01-17 11:24 UTC, trukhilio commented on client/src/pages/AdminDefaultsPage/components/DashboardDomains.tsx
> +      <FieldArray name="dashboardDomains">
Create constant `dashboardDomains` and reuse it in a file

2023-01-17 11:24 UTC, trukhilio commented on client/src/pages/AdminDefaultsPage/components/DashboardDomains.tsx
> +                            component={InputAdapter as any}
Try to fix `any` type

2023-01-17 11:24 UTC, trukhilio commented on client/src/pages/AdminDefaultsPage/components/InputAdapter.tsx
> +  [key: string]: any;
Try to fix all `any` types

2023-01-17 11:24 UTC, trukhilio commented on client/src/pages/AdminDefaultsPage/components/SearchPostfixes.tsx
> +  form: FormApi<any>;
Fix `any` type

2023-01-17 11:24 UTC, trukhilio commented on client/src/pages/AdminDefaultsPage/components/SearchPostfixes.tsx
> +    form.mutators.push('searchPostfixes', {
Create const for `searchPostfixes` and reuse

2023-01-17 11:24 UTC, trukhilio commented on client/src/pages/AdminDefaultsPage/components/SearchPostfixes.tsx
> +                            component={InputAdapter as any}
Try to fix `any` type here too

2023-01-17 11:24 UTC, trukhilio commented on client/src/pages/AdminDefaultsPage/components/SearchPrefixes.tsx
> +  form: FormApi<any>;
Fix `any` type

2023-01-17 11:24 UTC, trukhilio commented on client/src/pages/AdminDefaultsPage/components/SearchPrefixes.tsx
> +    form.mutators.push('searchPrefixes', {
Reuse `searchPrefixes` please

2023-01-17 11:24 UTC, trukhilio commented on client/src/pages/AdminDefaultsPage/components/UsernamesOnCustomDomains.tsx
> +import classes from '../styles/AdminDefaultsPage.module.scss';
Please move classes to the bottom of the imports

2023-01-17 11:24 UTC, trukhilio commented on client/src/pages/AdminDefaultsPage/components/UsernamesOnCustomDomains.tsx
> +  form: FormApi<any>;
Fix `any` type

2023-01-17 11:24 UTC, trukhilio commented on client/src/pages/AdminDefaultsPage/components/UsernamesOnCustomDomains.tsx
> +    form.mutators.push('usernamesOnCustomDomains', {
Reuse `usernamesOnCustomDomains`

2023-01-17 11:24 UTC, trukhilio commented on client/src/pages/AdminDefaultsPage/components/UsernamesOnCustomDomains.tsx
> +                            component={InputAdapter as any}
Fix `any`

2023-01-17 11:24 UTC, trukhilio commented on client/src/pages/AdminDefaultsPage/dndUtils.ts
> +export const makeOnDragEndFunction = (fields: any) => (result: any) => {
Try to fix `any`

2023-01-17 11:24 UTC, trukhilio commented on client/src/pages/AdminDefaultsPage/styles/AdminDefaultsPage.module.scss
> +  border: 1px solid #ebebeb;
Please use colors constants from colors file

2023-01-17 11:24 UTC, trukhilio commented on client/src/pages/AdminDefaultsPage/index.ts
> +import AdminDetaultsPage from './AdminDetaultsPage';
You could use `export { default } from './AdminDetaultsPage';`

2023-01-17 11:24 UTC, trukhilio commented on client/src/pages/AdminPartnersListPage/components/updatePartner/PartnerFormDomainRow.tsx
> +    (e: any) => {
Try to fix `any`

2023-01-17 11:24 UTC, trukhilio commented on server/src/models/Base.mjs
> +
Why there is an extra empty line?

2023-01-17 11:24 UTC, trukhilio commented on client/src/pages/AdminDefaultsPage/components/UsernamesOnCustomDomains.tsx
> +    <div className={classes.section}>
I see that all of the components has the same structure. It would be awesome to create some FieldsArrayContainer and pass unique things there.

2023-01-17 16:16 UTC, vmkarpenko commented on client/src/pages/AdminPartnersListPage/components/updatePartner/PartnerFormDomainRow.tsx
> +    (e: any) => {
I guess it should be `React.ChangeEvent`

2023-01-17 16:20 UTC, vmkarpenko commented on client/src/pages/AdminDefaultsPage/components/AvailableDomains.tsx
> +                            component={InputAdapter as any}
we have `Input` component. is it not work for this case?

2023-01-18 08:04 UTC, trukhilio requested changes
Check comments please

2023-01-18 08:04 UTC, trukhilio commented on client/src/pages/AdminDefaultsPage/components/SearchPostfixes.tsx
> +    (index: number, fields: any) => {
Try to fix `any`

2023-01-18 08:04 UTC, trukhilio commented on client/src/pages/AdminDefaultsPage/components/SearchPrefixes.tsx
> +import classes from '../styles/AdminDefaultsPage.module.scss';
Add empty lines here too

2023-01-18 08:04 UTC, trukhilio commented on client/src/pages/AdminDefaultsPage/components/SearchPrefixes.tsx
> +    (index: number, fields: any) => {
Try to fix `any`

2023-01-18 08:04 UTC, trukhilio commented on client/src/pages/AdminDefaultsPage/components/SearchPrefixes.tsx
> +                            component={InputAdapter as any}
Try to fix `any` here.

2023-01-18 08:04 UTC, trukhilio commented on client/src/pages/AdminDefaultsPage/components/UsernamesOnCustomDomains.tsx
> +    (index: number, fields: any) => {
Try to fix `any`

2023-01-18 10:39 UTC, trukhilio approved these changes
Check comment

2023-01-18 10:39 UTC, trukhilio commented on client/src/pages/AdminDefaultsPage/styles/AdminDefaultsPage.module.scss
> +  border: 1px solid $desert-storm;
Change border color too please

2023-01-18 10:51 UTC, trukhilio approved these changes

2023-01-18 10:51 UTC, merged